# Subproject of loopin:boxing for alphabox building and deployment
# Please use http://buildr.apache.org/
require 'time'

# Helpers for project definition
my_name = File.basename(File.dirname(__FILE__))
my_version = 'LATEST.' << Time.now.utc.iso8601(3).gsub(/\W/, '')
my_layout = Layout.new
my_layout[:target] = File.expand_path("../../../upload",__FILE__)

# Special handling if project will be included as a sub-project
if Buildr.application.current_scope.empty? then
  # Define custom build goal symbols as global ones
  [:up, :down].each{ |taskname| Project.local_task taskname}
  scope = ''
else
  scope = Buildr.application.current_scope.join(':').concat(':')
end


# Start project and build goals definition
define "#{scope}#{my_name}", :version=>my_version, :layout=>my_layout do

  desc "Start VM from box #{my_name}"
  task :up do
    raise "Error for vagrant up: #{$?.exitstatus.to_s}" unless system "vagrant up #{my_name}"
  end

  desc "Destroy VM #{my_name}"
  task :down do
    raise "Error for vagrant destroy: #{$?.exitstatus.to_s}" unless system "vagrant destroy #{my_name} --force"
  end

  desc "Build box #{my_name}"
  build do
    cd File.expand_path("../packer",__FILE__) do
      raise "Error in packer: #{$?.exitstatus.to_s}" unless system "packer build packer.json"
    end
  end

  desc "Clean up box #{my_name}"
  clean do
    rm_rf ["#{self.layout[:target]}/#{my_name}.box"]
    system "vagrant box remove #{my_name}"
  end
end