# Subproject of loopin:boxing for ubuntu-vivid building deployment
# Please use http://buildr.apache.org/
require 'time'

name = File.basename(File.dirname(__FILE__))
version = 'LATEST.' << Time.now.utc.iso8601(3).gsub(/\W/, '')
layout = Layout.new.tap { |me| me[:target]='../../upload' }
scope = Buildr.application.current_scope.empty? ? '' : Buildr.application.current_scope.join(':').concat(':')

# Start project and build goals definition
define "#{scope}#{name}", :version=>version, :layout=>layout do

  desc "Start VM from box #{self.name}"
  task :up do
    raise "Error for vagrant up: #{$?.exitstatus.to_s}" unless system "vagrant up #{self.name}"
  end 

  desc "Destroy VM #{self.name}"
  task :down do
    raise "Error for vagrant destroy: #{$?.exitstatus.to_s}" unless system "vagrant destroy #{self.name} --force"
  end 

  desc "Build box #{self.name}"
  build do
    cd 'packer' do
      raise "Error in packer: #{$?.exitstatus.to_s}" unless system "packer build packer.json"
    end
  end

  desc "Clean up box #{self.name}"
  clean do
    rm_rf ["#{self.layout[:target]}/#{self.name}.box"]
    system "vagrant box remove #{self.name}"
  end
end

# Define custom build goal symbols as global ones
[:up, :down].each{ |taskname| Project.local_task taskname}