# Subproject of loopin:provisioning for login puppet module testing
# Please use http://buildr.apache.org/
require 'time'

# Helpers for project definition
my_name = File.basename(File.dirname(__FILE__))
my_version = 'LATEST.' << Time.now.utc.iso8601(3).gsub(/\W/, '')

# Special handling if project will be included as a sub-project
if Buildr.application.current_scope.empty? then
  # Define custom build goal symbols as global ones
  [:up, :down].each{ |taskname| Project.local_task taskname}
  scope = ''
else
  scope = Buildr.application.current_scope.join(':').concat(':')
end


# Here we start with project and build goals definition
define "#{scope}#{my_name}", :version=>my_version do

  box = "puppet-#{my_name}"

  desc "Start VM from box #{box}"
  task :up do
    raise "Error for vagrant up: #{$?.exitstatus.to_s}" unless system "vagrant up #{box}"
  end

  desc "Destroy VM #{box}"
  task :down do
    raise "Error for vagrant destroy: #{$?.exitstatus.to_s}" unless system "vagrant destroy #{box} --force"
  end
end