# Subproject of loopin:boxing for alphabox building deployment
# Please use http://buildr.apache.org/
require 'time'

# BOXES is name of project and containing folder
path = File.expand_path("..",__FILE__)
name = File.basename(path)
version = 'LATEST.' << Time.now.utc.iso8601(3).gsub(/\W/, '')
layout = Layout.new.tap { |me| me[:target]='../upload' }
# Start project and build goals definition
define name, :version=>version, :layout=>layout do

  Dir["#{path}/*/Buildfile"].each { |file| load file }

  desc "Destroy any VM #{self.name}"
  task :downall do
    puts "Need implementation to trigger all tasks of subprojects :down tasks"
  end 

  desc "Clean any box #{self.name}"
  task :cleanall do
    puts "Need implementation to trigger all tasks of subprojects :clean tasks"
  end
end

# Define custom build goal symbols as global ones
[:downall, :cleanall].each{ |taskname| Project.local_task taskname}