# Project boxing for building vagrant boxes
# Please use http://buildr.apache.org/
require 'time'

# Helpers for project definition
my_version = 'LATEST.' << Time.now.utc.iso8601(3).gsub(/\W/, '')
my_layout = Layout.new
my_layout[:target] = File.expand_path("../../upload",__FILE__)

# Start project and build goals definition
define 'boxing', :version=>my_version, :layout=>my_layout do

  path = File.expand_path("..",__FILE__)
  Dir["#{path}/*/Buildfile"].each { |file| load file }

  desc "Destroy any VM of boxing sub-projects"
  task :downall do
    project.projects.map{ |child| task("#{child.name}:down") }.each do |down|
      down.execute unless down.nil?
    end
  end 

  desc "Clean any box of sub-projects"
  task :cleanall do
    project.projects.map{ |child| task("#{child.name}:clean") }.each do |clean|
      clean.execute unless clean.nil?
    end
  end
end

# Define custom build goal symbols as global ones
[:downall, :cleanall].each{ |taskname| Project.local_task taskname}